services:
  - type: web
    name: learnix-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && PYTHONPATH=. python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION
        value: learnix_documents
      - key: GEMINI_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
